### ISSUE TITLE
receiving emails (how does it work? documentation)

### ISSUE THREAD

**Issue by streaps** [emersion/neutron#30]
I don't understand how a full setup for receiving and sending emails works.

For sending emails, neutron uses an external smtp server. (?)

How does it receive emails? What is stored on the IMAP server? encrypted or unencrypted emails?

Is the stored data (emails) fully encrypted?

**Comment by emersion** [comment]
You're right, this project needs better docs. Will do that tomorrow.

**Comment by emersion** [comment]
Just updated the README to make it clearer. Just let me know if you have more questions.

**Comment by streaps** [comment]
Thank you, it's clearer now.

If I understand it correctly I can use (and I need) a standard mail server (e.g. Postfix + Dovecot IMAP) with neutron.

Emails between local neutron users are always encrypted.

**Comment by emersion** [comment]
That's it!
