### ISSUE TITLE
Make Start (and make build-docker) fail

### ISSUE THREAD

**Issue by kindsouls** [emersion/neutron#39]
I am running CentOS 7. I've successfully built Neutron as instructed. However, when I run make start or make build-docker I get the same error:

make start
go run neutron.go
# github.com/emersion/neutron/backend/imap
backend/imap/attachments.go:40: undefined: imap.NewSeqSet
backend/imap/events.go:40: undefined: imap.NewSeqSet
backend/imap/messages.go:44: undefined: imap.NewSeqSet
backend/imap/messages.go:159: undefined: imap.NewSeqSet
backend/imap/messages.go:389: undefined: imap.NewSeqSet
backend/imap/messages.go:532: undefined: imap.NewSeqSet
make: *** [start] Error 2

Thanks for any assistance!

**Comment by ghost** [comment]
Got the same error, haven't found a solution yet.

**Comment by emersion** [comment]
This is caused by a go-imap breaking change. I just pushed a fix for neutron!

Neutron should really use either glide or dep to pin dependencies and prevent such issues.
