### ISSUE TITLE
How to configure Apache with HTTPS to proxy requests to Neutron?

### ISSUE THREAD

**Issue by kindsouls** [emersion/neutron#41]
I've built neutron using go. I've setup my SSL cert using Letsencrypt. 
I can see the Protonmail server at port 4000, and I can see the CentOS test page at port 443. 

Running "make start" to get Macaron to listen on port 4000. But, I cannot figure out how to get the server to use SSL for neutron. Any help would be greatly appreciated! 

Thank!

**Comment by emersion** [comment]
Usually, a reverse proxy is used for that:

```
Internet ---[HTTPS]---> Reverse proxy ----[HTTP]-----> Neutron
```

So you have to configure your web server (apache/nginx/caddy...) to:
* Use your certificate
* Proxy requests to `localhost:4000`

**Comment by kindsouls** [comment]
Please, forgive my ignorance, but I've setup the reverse proxy server, and can connect to the default apache page via https.  

I can access the login page for Proton using the URL I've assigned.... but I cannot get it to use the LetsEncrypt SSL. That is to say that http://myurl.com works, but https://myurl.com does not (https brings up the default Apache page for CentOS). 

My httpd.conf file has the following VirtualHost info in it:


<VirtualHost *:80>
    ProxyPreserveHost On

    ProxyPass / http://45.33.93.249:4000/
    ProxyPassReverse / http://45.33.93.249:4000/
</VirtualHost>

<VirtualHost *:443>
    ProxyPreserveHost On

    ProxyPass / http://45.33.93.249:4000/
    ProxyPassReverse / http://45.33.93.249:4000/
</VirtualHost>

How does one specify forced SSL connections using CentOS 7 and Node.js (presumably)?

**Comment by emersion** [comment]
Sorry, the last time I wrote an Apache config file was a really long time ago. I won't be of any help here! :\

**Comment by kindsouls** [comment]
Thanks anyway!

**Comment by streaps** [comment]
Do you have "SSLEngine on" in the VirtualHost config?

```
<VirtualHost *:443>
        SSLEngine on
        SSLCertificateFile      /etc/ssl/star.example.com.crt
        SSLCertificateKeyFile   /etc/ssl/star.example.com.key
...
```
see https://wiki.apache.org/httpd/NameBasedSSLVHosts

**Comment by kindsouls** [comment]
Adding  SSLEngine on does not change the CentOS Apache default page from showing up.

Here's my entry in httpd.conf. HTTP works, HTTPS does not.

<VirtualHost *:80>
    ProxyPreserveHost On

    ProxyPass / http://xx.xx.xx.xx:4000/
    ProxyPassReverse / http://xx.xx.xx.xx:4000/
</VirtualHost>

<VirtualHost *:443>
    SSLProxyEngine on

    SSLEngine on
    SSLCertificateFile      /etc/letsencrypt/live/domainname.org/cert.pem
    SSLCertificateKeyFile   /etc/letsencrypt/live/domainname.org/privkey.pem

    ProxyPreserveHost On
    ProxyRequests Off
    ProxyPass / http://xx.xx.xx.xx:4000/
    ProxyPassReverse / http://xx.xx.xx.xx:4000/
</VirtualHost>

**Comment by streaps** [comment]
Try using your Hostname instead of the *

<VirtualHost mail.example.org:443>

**Comment by streaps** [comment]
I haven't used Apache for a while, I don't know if this helps...

Do you have

    ServerName mail.example.org

set?

Is there another `<VirtualHost xx.xx.xx.xx:443>` somewhere in the configs?

Have you tried using` <VirtualHost xx.xx.xx.xx:443>` instead of `<VirtualHost *:443>`?

**Comment by streaps** [comment]
Btw, is there a way to bind the neutron http server to localhost?

**Comment by emersion** [comment]
@streaps Yes, you can change the `PORT` and `HOST` environment variables (source: https://go-macaron.com/docs/faqs).

**Comment by kindsouls** [comment]
thank you streaps. Adding the IP instead of a wildcard worked like a charm! On to my next problem, for which I'll create a new issue. 
Thank you again!
